void jl_new_int_test;
void jl_new_float_test;
void jl_new_string_test;
void jl_new_array_test;
void jl_object_free_test;
void jl_length_test;
void jl_add_test;
void jl_array_set_test;
void jl_array_get_test;
